name: Deploy server to Heroku

on:
  push:
    branches:
      - master
    paths:
      - "packages/server/**"
      - ".github/workflows/server.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add server remote origin
        run: git remote add leonardomso-playground-server https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_SERVER_NAME }}.git
      - name: Deploy server to Heroku
        run: git push leonardomso-playground-server `git subtree split --prefix leonardomso-playground-server master`:refs/heads/master --force
