name: Deploy web to Heroku

on:
  push:
    branches:
      - master
    paths:
      - "packages/web/**"
      - ".github/workflows/web.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add web remote origin
        run: git remote add leonardomso-playground-web https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_WEB_NAME }}.git
      - name: Deploy web to Heroku
        run: git push leonardomso-playground-web `git subtree split --prefix web master`:refs/heads/master --force
